services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: intercambio_db
      POSTGRES_USER: intercambio_user
      POSTGRES_PASSWORD: intercambio_pass
    ports:
      - "5443:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    restart: always
    ports:
      - "8002:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - backend
volumes:
  postgres_data:
